language: python

python:
    - 2.7
    - 3.5

sudo: false

notifications:
  email: false

git:
  depth: 1

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - if [[ ${TRAVIS_PYTHON_VERSION::1} -eq 2 ]]; then
         pip -q install coveralls;
      fi
    - python setup.py develop

script:
    - if [[ ${TRAVIS_PYTHON_VERSION::1} -eq 2 ]]; then
        coverage run test/test.py;
      else
        nosetests -v test/test.py;
      fi

after_success:
    - if [[ ${TRAVIS_PYTHON_VERSION::1} -eq 2 ]]; then
        coveralls;
      fi
