language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
  - 3.6
  - 3.7

os:
  - linux

env: FC=gfortran-6


addons:
  apt:
#    sources:
#      - ubuntu-toolchain-r-test
    packages:
#      - gfortran-6
      - octave

# FIXME: temporary for travis xenial
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -yq gfortran-6

install: 
  - pip install -e .[tests,full]

  - cd bin
  - cmake ..
  - cmake --build .

script: 
  - ctest -V
  - cd ..

  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

