[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
known_third_party = ["pymap3d"]

[tool.mypy]
files = ["src", "Examples", "scripts"]

strict = true
ignore_missing_imports = true
strict_optional = false
show_column_numbers = true
show_error_codes = true

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:Tried to get polar motions for times before IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the arcsec level. Please check your astropy.utils.iers.conf.iers_auto_url and point it to a newer version if necessary",
    "ignore:divide by zero encountered in (divide|double_scalars):RuntimeWarning",
    "ignore:This function is deprecated.*pyproj:DeprecationWarning",
    "ignore:invalid value encountered in (divide|arcsin):RuntimeWarning",
]

[tool.coverage.run]
branch = true
source = "src/"

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",
    # Don't complain about function overloading
    "@overload",
]
