name: ci

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/ci.yml
      - "!scripts/"
  pull_request:
    paths:
      - "**.py"
      - .github/workflows/ci.yml

jobs:
  full:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.11"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tests and lint dependencies
        run: pip install -e .[tests,lint]

      - name: Lint
        run: flake8
      - name: Type check
        run: mypy

      - name: Test stdlib and collect coverage
        run: pytest --cov=src --cov-report=xml

      - name: Install NumPy
        run: pip install numpy
      - name: Test with NumPy and collect coverage
        run: pytest --cov=src --cov-report=xml --cov-append

      - name: Install full dependencies
        run: pip install -e .[full]
      - name: Test with full dependencies and collect coverage
        run: pytest --cov=src --cov-report=xml --cov-append

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          name: ${{ matrix.os }} Python ${{ matrix.python-version }}
